version: '3'

networks:
  julolle-net:
    name: julolle-net
    driver: bridge

services:
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env 
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - julolle-net

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html     
    networks:
      - julolle-net

  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress
    depends_on:
      - mariadb    
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - julolle-net

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/julolle-/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/julolle-/data/wordpress
      o: bind
