services:
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: wordpress
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pass
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
  wordpress_data:
